# Generated by Django 6.0.6 on 2026-06-24 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[("modern", "Modern"), ("traditional", "Traditional")],
                        max_length=20,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("ar_layout", models.JSONField(default=dict)),
                ("sound_mapping", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="ScanLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.instrument",
                    ),
                ),
            ],
        ),
    ]
